### ISSUE TITLE
Support getting the build scan url on build failure

### ISSUE THREAD

**Issue by eskatos** [eskatos/gradle-command-action#1]
The action currently fails when the Gradle execution fails. It means that the `build-scan-url` output can only be consumed by subsequent steps when the Gradle execution succeeds.

This issue is about adding support for not failing the action when the Gradle execution fails so that subsequent steps can decide what to do and use the build scan url.

Something along those lines:

```yaml
steps:
- name: gradle 
  uses: eskatos/gradle-command-action@v1
  with:
    arguments: build --scan
    failOnError: false
- name: "publish build scan"
  uses: some/action@v42
  with:
    content: "Build Scan ${{ steps.gradle.outputs.build-scan-url }}"
- name: "check gradle exit code"
  run: test ${{ steps.gradle.outputs.status }} == 0
  shell: bash
```
