### ISSUE TITLE
Publish build scan URL

### ISSUE THREAD

**Issue by jmfayard** [eskatos/gradle-command-action#10]
Hello @eskatos 

I tried to include the build scan URL in the github message but didn't succeed.

> Build scans
> If your build publishes a build scan the gradle-command-action action will emit the link to the published build scan as an output named build-scan-url.
> You can then use that link in subsequent actions of your workflow.

Here is my yaml config

```yaml
name: CI unit tests
on: [pull_request]
jobs:
  unittests:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: testDebugUnitTest
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        if: failure()
        with:
          message: Build failed ${{ steps.gradle.outputs.build-scan-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}     
```

Expected result: `Build failed https://gradle.com/s/rjfaddrnmi5dq`
Actual result: `Build failed`

PR https://github.com/jmfayard/android-kiss/pull/5

Actions: https://github.com/jmfayard/android-kiss/actions

**Comment by eskatos** [comment]
Hey @jmfayard,

Sorry for the lag answering your question. It works for me™.

Your workflow file points to `steps.gradle.outputs.build-scan-url` but your step running the gradle action doesn't declare an `id`.

Here's the excerpt from the README:

```yaml
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
      id: gradle
    - uses: example/action-that-comments-on-the-pr@v0
      if: failure()
      with:
        comment: Build failed ${{ steps.gradle.outputs.build-scan-url }}
```

The key is the 4th line `id: gradle`.

I'm optimistically closing this, feel free to reopen if it doesn't work for you.
