### ISSUE TITLE
Fail: Gradle 5.2.1 - Java 8 - Kotlin DSL

### ISSUE THREAD

**Issue by nekkan** [eskatos/gradle-command-action#14]
Why is my build failing?

```vbs
> Configure project :
Compiling Discord4K version "1.0.0-SNAPSHOT"
Compiling subproject 'd4k-api'...
Compiling subproject 'd4k-sdk'...
Could not resolve compiler classpath. Check if Kotlin Gradle plugin repository is configured in root project 'Discord4K'.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileKotlin'.
> Could not resolve all files for configuration ':kotlinCompilerClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.71 because no repositories are defined.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
```
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
```

[build.gradle.kts](https://github.com/nekkan/Discord4K/blob/master/build.gradle.kts)
