### ISSUE TITLE
"##[error]versionSpec parameter is required" when using `rc` Gradle version

### ISSUE THREAD

**Issue by mateuszkwiecinski** [eskatos/gradle-command-action#29]
Hello 👋  
When using 
```
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: sample
          gradle-version: rc
          dependencies-cache-enabled: true
          arguments: (...)
```
I'm getting `"##[error]versionSpec parameter is required"` error message 
![image](https://user-images.githubusercontent.com/36954793/91358118-8d7b6e80-e7f2-11ea-9d5f-61888fdd3e75.png)

I tested with different arguments `6.1.1, current, rc, nightly, release-nightly` but only `rc` fails with such message. According to the [documentation](https://github.com/eskatos/gradle-command-action#setup-and-use-a-declared-gradle-version) even if it is not available it should fallback to `current`. Or do I get something wrong? 

Thanks for creating and maintaining the plugin 👍
