### ISSUE TITLE
Dependency caching issues

### ISSUE THREAD

**Issue by pavlospt** [eskatos/gradle-command-action#35]
Hello, continuing a short discussion we had on Gradle slack group with this issue :) 

Our previous setup for Gradle caching was the following:
```yaml
- uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
```

in order to cache the wrapper only.

After switching to this Github action, Wrapper caching works just like before, but we have seen that there was an increase in amount of time spent to execute a step of the job, which was previously using Gradle directly.

Our current GCA configuration is the following:
```yaml
- uses: eskatos/gradle-command-action@v1
        name: Run Spotless Kotlin check
        with:
          arguments: spotlessKotlinCheck
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
```
for the steps that execute Gradle commands.

Although, we see the following logs in the Jobs execution:
```
Received 188743680 of 265189797 (71.2%), 179.8 MBs/sec
Received 265189797 of 265189797 (100.0%), 153.6 MBs/sec
Cache Size: ~253 MB (265189797 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/1bfe5e14-fe54-49ed-9be7-e82e07e1fc21/cache.tzst -P -C /home/runner/work/our_project
Wrapper installation restored from cache key: wrapper-6.6.1-all
Received 218103808 of 252537189 (86.4%), 207.8 MBs/sec
Received 252537189 of 252537189 (100.0%), 150.1 MBs/sec
Cache Size: ~241 MB (252537189 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/24e14abe-50f6-4f0c-ac36-a572622446b8/cache.tzst -P -C /home/runner/work/our_project
Dependencies restored from cache key: dependencies-0b71f356b09000f604bde0cdb6a19decb186c474a46cf0dd90af311471bd403e
Received 318 of 318 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (318 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/55187232-a2b1-4d0c-aa79-6f6d01b2f81b/cache.tzst -P -C /home/runner/work/our_project
Configuration restored from cache key: configuration-7b33f41d52b4b4df03f055a384afe740cbd081f30e897366495d6e891ddd4948
/home/runner/work/our_project/gradlew spotlessKotlinCheck
```
As you can see there is no dependencies cached.

Another thing we have tried for the dependency caching issue, was trying to specify the files we needed to be checked and used for dependency-cache invalidation, like following:
```yaml
          dependencies-cache-key: |
            *.gradle.kts
            gradle-wrapper.properties
            *Deps.kt
            SharedVersions.kt
```
This didn't work either though and we kept getting the same logs in the Job's execution.

All of our jobs run on `ubuntu-latest`. Let me know if there is anything unclear or how I can provide more information to help debug the issue 😄
