### ISSUE TITLE
Don't execute the gradle-command when no arguments are given

### ISSUE THREAD

**Issue by blatobi** [eskatos/gradle-command-action#39]
I would like to separate some gradle tasks into their own steps to:

- use other actions like [gradle-wrapper-validation](https://github.com/marketplace/actions/gradle-wrapper-validation)
- allowing to read outputs from gradle into the environment
- restricting sensitive env-tokens to specific steps

Separation is already possible if "arguments" only contains "--version". At least the following seems to work fine:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Build
      - name: Set up Java [...]
      - name: cache gradle
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: --version
      - name: store some config info in Environment
        run: echo "CONFIG_INFO=`./gradlew -q someConfigInfo`" >> $GITHUB_ENV
      - name: build and push
        env:
          USER: "..."
          TOKEN: "..."
        run: ./gradlew clean jib
```
It would be :tada: if this action does not force the usage of arguments and by this allowing users to only utilize the excellent caching-mechanism.
