### ISSUE TITLE
"wrapper-directory" doesn't run my "gradlew"

### ISSUE THREAD

**Issue by MarounMaroun** [eskatos/gradle-command-action#4]
I'm trying to use my `gradlew`, which's delivered as part of the project in the root's folder, but seems like everytime I'm getting a newly downloaded `gradlew`, and not using the one I already have.

Here's my code:

```yml
steps:
- uses: actions/checkout@v1
- name: Set up JDK 1.11
  uses: actions/setup-java@v1
  with:
    java-version: 1.11
- uses: eskatos/gradle-command-action@v1
  with:
    wrapper-directory: .
    arguments: clean build -P<property> -P<property>
```

Am I misusing the action?
