### ISSUE TITLE
Ignores build-root-directory

### ISSUE THREAD

**Issue by cfogelklou** [eskatos/gradle-command-action#44]
Please see the following run:
https://github.com/cfogelklou/android_auto_test_ci_cd/actions/runs/635280555

```
- name: Build for Android Automotive
        uses: eskatos/gradle-command-action@v1.3.0
        with:
          build-root-directory: uamp
          arguments: assemble
```

But it results in the error:

```
Error: ENOENT: no such file or directory, open '/home/runner/work/android_auto_test_ci_cd/android_auto_test_ci_cd/gradle/wrapper/gradle-wrapper.properties'
```
It should **not** be running in ```/home/runner/work/android_auto_test_ci_cd/android_auto_test_ci_cd/gradle/```

It should be running in``` /home/runner/work/android_auto_test_ci_cd/android_auto_test_ci_cd/uamp/gradle``` as uamp is the specified subdirectory.
