### ISSUE TITLE
`wrapper` version

### ISSUE THREAD

**Issue by musketyr** [eskatos/gradle-command-action#5]
I would like to have also a special version called `wrapper`. If I understand it properly then if no `gradle-version` argument is sent then the wrapper is used. I would like to be able to do the following to be able to test against multiple versions of Gradle and the wrapper as well.

```
    strategy:
      fail-fast: false
      matrix:
        gradle:
        - 6.0.1
        - 5.6.4
        - 5.5.1
        - 5.4.1
        - 5.3.1
        - 5.2.1
        - 5.1.1
        - wrapper
```
