### ISSUE TITLE
Cache wrapper and other caches between builds

### ISSUE THREAD

**Issue by eskatos** [eskatos/gradle-command-action#7]
Github Actions agents are ephemeral, Gradle builds need to download the Gradle distribution, generate API jars, download dependencies etc... All this could be avoided on repeated builds by caching the relevant Gradle caches.

One can use https://github.com/marketplace/actions/cache Today but it requires some boilerplate:

```yaml
- uses: actions/cache@v1
  with:
    path: ~/.gradle/wrapper
    key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
- uses: actions/cache@v1
  with:
    path: ~/.gradle/caches
    key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    restore-keys: |
      ${{ runner.os }}-gradle-caches-
```

This issue is about reusing `actions/cache` mechanism from this very action to reduce that boilerplate.

Blocked on https://github.com/actions/cache/issues/55
