### ISSUE TITLE
Environment variable not resolve in arguments

### ISSUE THREAD

**Issue by eaxdev** [eskatos/gradle-command-action#8]
Hello, @eskatos . I using your action in my build. I want use environment variable in arguments:

```yml
 - name: Publish with Gradle
        env:
          RELEASE_VERSION: ${GITHUB_REF:11}
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: test publish -Pversion=$RELEASE_VERSION
```

But, it not work for me. I get this result of this step:

```
/home/runner/gradle-provision-tmpdir/installs/gradle-6.1.1/bin/gradle test publish -Pversion=$RELEASE_VERSION
```

My env variable not resolve, and set as is. How can I set this variable for gradle param? Thx,
